import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { copyFileSync, mkdirSync, readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { STRIP_FILTER, stripScriptInjectionSource } from './esbuild/strip-script-injection.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const buildDir = resolve(__dirname, 'build');

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

/**
 * Neutralizes dead-code <script>-injection feature-detection branches that ship
 * inside transitive deps. The filter + transform live in
 * ./esbuild/strip-script-injection.mjs so they can be unit-tested outside a full
 * build (esbuild/strip-script-injection.test.mjs) — see that module for the full
 * rationale, drift-safety contract, and why the culprit deps are version-pinned.
 */
const stripScriptInjectionPlugin = {
	name: "strip-script-injection",
	setup(build) {
		build.onLoad({ filter: STRIP_FILTER }, (args) => {
			const src = readFileSync(args.path, "utf8");
			// "js" loader auto-detects ESM (.mjs) vs CJS — fine for all target files.
			return { contents: stripScriptInjectionSource(src), loader: "js" };
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	// Obsidian plugins run in Electron (Node.js environment), so we target
	// node to ensure Node.js-specific modules (e.g., AWS SDK credential
	// providers with fromIni) resolve their Node.js bundles rather than
	// the browser stubs that omit those exports.
	platform: "node",
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "build/main.js",
	minify: prod,
	plugins: [stripScriptInjectionPlugin],
});

/**
 * Copy manifest.json and styles.css into build/ so the build directory
 * contains all artifacts Obsidian needs to load the plugin.
 */
function copyPluginAssets() {
	mkdirSync(buildDir, { recursive: true });
	copyFileSync(resolve(__dirname, 'manifest.json'), resolve(buildDir, 'manifest.json'));
	try {
		copyFileSync(resolve(__dirname, 'styles.css'), resolve(buildDir, 'styles.css'));
	} catch {
		// styles.css is optional
	}
	console.log('[build] Copied manifest.json and styles.css to build/');
}

/**
 * Hard safety contract: fail the build if any createElement("script") /
 * createElement('script') literal survives in the emitted bundle. The Obsidian
 * community-plugin reviewer rejects dynamic script-element creation as a hard
 * Error, so we must never ship one.
 */
function verifyNoScriptInjection() {
	const bundle = readFileSync(resolve(buildDir, 'main.js'), 'utf8');
	const matches = bundle.match(/createElement\((['"])script\1\)/g) || [];
	if (matches.length > 0) {
		console.error(
			`\n[build] FAILED: build/main.js contains ${matches.length} ` +
			`createElement("script") literal(s).\n` +
			`The Obsidian reviewer rejects dynamic script-element creation as a hard Error.\n` +
			`These come from dead browser/IE feature-detection branches in ` +
			`immediate / setimmediate / docx. A dependency bump likely changed the code ` +
			`shape so strip-script-injection's TEST_RE / BODY_RE no longer match — ` +
			`inspect the survivors and update the regexes in esbuild.config.mjs.\n`
		);
		process.exit(1);
	}
	console.log('[build] Verified: 0 createElement("script") literals in build/main.js');
}

if (prod) {
	await context.rebuild();
	copyPluginAssets();
	verifyNoScriptInjection();
	process.exit(0);
} else {
	// In dev/watch mode, also copy assets once at startup
	copyPluginAssets();
	await context.watch();
}
