import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { copyFileSync, mkdirSync, readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const buildDir = resolve(__dirname, 'build');

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

/**
 * Neutralizes dead-code <script>-injection feature-detection branches that ship
 * inside transitive deps (immediate, setimmediate) and docx's pre-bundled dist.
 * These are IE6-8 / browser-only async-scheduler fallbacks that NEVER execute
 * under Node/Electron (we run process.nextTick / native setImmediate). Removing
 * the literal document.createElement("script") text lets the Obsidian
 * community-plugin reviewer's "dynamic script element creation" check pass.
 * Runtime behavior is unchanged — the node code paths are untouched.
 */
const stripScriptInjectionPlugin = {
	name: "strip-script-injection",
	setup(build) {
		// Scope tightly to the three resolved culprit files (also docx cjs variants
		// in case resolution ever picks the require path). [\\/] = cross-platform.
		const filter =
			/(immediate[\\/]lib[\\/]index\.js|setimmediate[\\/]setImmediate\.js|docx[\\/]dist[\\/]index\.(mjs|cjs|umd\.cjs))$/;

		// (A) turn the feature TEST false -> esbuild folds the if-block / ternary arm away.
		const TEST_RE =
			/(['"])onreadystatechange\1\s*in\s+[\w$.]+\.createElement\((['"])script\2\)/g;
		// (B) rewrite any remaining BODY literal -> result is independent of esbuild DCE.
		const BODY_RE = /\bcreateElement\((['"])script\1\)/g;

		build.onLoad({ filter }, (args) => {
			const src = readFileSync(args.path, "utf8");
			const contents = src
				.replace(TEST_RE, "false")
				.replace(BODY_RE, 'createElement("template")');
			// "js" loader auto-detects ESM (.mjs) vs CJS — fine for all three files.
			return { contents, loader: "js" };
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	// Obsidian plugins run in Electron (Node.js environment), so we target
	// node to ensure Node.js-specific modules (e.g., AWS SDK credential
	// providers with fromIni) resolve their Node.js bundles rather than
	// the browser stubs that omit those exports.
	platform: "node",
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "build/main.js",
	minify: prod,
	plugins: [stripScriptInjectionPlugin],
});

/**
 * Copy manifest.json and styles.css into build/ so the build directory
 * contains all artifacts Obsidian needs to load the plugin.
 */
function copyPluginAssets() {
	mkdirSync(buildDir, { recursive: true });
	copyFileSync(resolve(__dirname, 'manifest.json'), resolve(buildDir, 'manifest.json'));
	try {
		copyFileSync(resolve(__dirname, 'styles.css'), resolve(buildDir, 'styles.css'));
	} catch {
		// styles.css is optional
	}
	console.log('[build] Copied manifest.json and styles.css to build/');
}

/**
 * Hard safety contract: fail the build if any createElement("script") /
 * createElement('script') literal survives in the emitted bundle. The Obsidian
 * community-plugin reviewer rejects dynamic script-element creation as a hard
 * Error, so we must never ship one.
 */
function verifyNoScriptInjection() {
	const bundle = readFileSync(resolve(buildDir, 'main.js'), 'utf8');
	const matches = bundle.match(/createElement\((['"])script\1\)/g) || [];
	if (matches.length > 0) {
		console.error(
			`\n[build] FAILED: build/main.js contains ${matches.length} ` +
			`createElement("script") literal(s).\n` +
			`The Obsidian reviewer rejects dynamic script-element creation as a hard Error.\n` +
			`These come from dead browser/IE feature-detection branches in ` +
			`immediate / setimmediate / docx. A dependency bump likely changed the code ` +
			`shape so strip-script-injection's TEST_RE / BODY_RE no longer match — ` +
			`inspect the survivors and update the regexes in esbuild.config.mjs.\n`
		);
		process.exit(1);
	}
	console.log('[build] Verified: 0 createElement("script") literals in build/main.js');
}

if (prod) {
	await context.rebuild();
	copyPluginAssets();
	verifyNoScriptInjection();
	process.exit(0);
} else {
	// In dev/watch mode, also copy assets once at startup
	copyPluginAssets();
	await context.watch();
}
